//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARIZADETAY
    {
        public int arizaid { get; set; }
        public Nullable<int> islemid { get; set; }
        public string sorun { get; set; }
        public string aciklama { get; set; }
        public Nullable<decimal> onfiyat { get; set; }
        public Nullable<decimal> netfiyat { get; set; }
        public string islemler { get; set; }
    }
}
