//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFATURADETAY
    {
        public int faturadetayid { get; set; }
        public string urun { get; set; }
        public Nullable<short> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public Nullable<int> faturaid { get; set; }
    
        public virtual TBLFATURABILGI TBLFATURABILGI { get; set; }
    }
}
