//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTLAR
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public Nullable<bool> okuma { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
