//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNHARAKET
    {
        public int haraketid { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<short> personel { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<short> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string urunserino { get; set; }
    
        public virtual TBLCARI TBLCARI { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
        public virtual TBLURUN TBLURUN { get; set; }
    }
}
