//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNKABUL
    {
        public int islemid { get; set; }
        public Nullable<int> cari { get; set; }
        public Nullable<short> personel { get; set; }
        public Nullable<System.DateTime> gelistarih { get; set; }
        public Nullable<System.DateTime> cikistarih { get; set; }
        public string urunserino { get; set; }
    
        public virtual TBLCARI TBLCARI { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
